### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by hefuyicoder** [macoscope/RoomBookerMVP#1]
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err: java.net.SocketTimeoutException: failed to connect to /10.0.2.2 (port 4567) after 10000ms
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:189)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:112)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.net.Socket.connect(Socket.java:898)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:197)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Connection.connectSocket(Connection.java:198)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Connection.connect(Connection.java:172)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:358)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:117)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:276)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:180)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:223)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:79)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:111)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:162)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:154)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:162)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:154)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:162)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable$2.call(Observable.java:154)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.Observable.unsafeSubscribe(Observable.java:7710)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-13 17:00:48.656 1404-7668/com.macoscpoe.roombooker W/System.err:     at java.lang.Thread.run(Thread.java:841)

**Comment by karthisammannan** [comment]
its working fine for me.please check your server .
